# -------- Stage 1: Build --------
FROM node:20-alpine AS build

WORKDIR /app

# Copia apenas package.json primeiro (melhora cache de build)
COPY package*.json ./

RUN npm install

# Copia o restante do projeto
COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build


# -------- Stage 2: Production (Nginx) --------
FROM nginx:alpine

# Copia build do Vite
COPY --from=build /app/dist /usr/share/nginx/html

# Configuração para SPA (React Router funcionar no refresh)
RUN echo 'server { \
  listen 80; \
  location / { \
    root /usr/share/nginx/html; \
    index index.html; \
    try_files $uri $uri/ /index.html; \
  } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]